version: '3.4'

services:
  desafiodotnet:
    image: ${DOCKER_REGISTRY-}desafiodotnet
    build:
      context: .
      dockerfile: DesafioDotNet/Dockerfile
    environment:
        DATABASE_URL: "Server=host.docker.internal,1233;Database=DesafioDb;User Id=sa;Password=!P4ssword;"      
  db:    
    build: 
        context: DesafioDotNet/SQL/        
    environment:
        SA_PASSWORD: "!P4ssword"
        ACCEPT_EULA: "Y"
    ports:
    - "1233:1433"
